name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Set up Go tip
      run: |
        go install -v golang.org/dl/gotip@latest
        gotip download -v

    - name: Build
      run: gotip build -v ./...

    - name: Test
      run: gotip test -v ./...
