name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Set up Go tip
        run: |
          go install -v golang.org/dl/go1.18beta1@latest
          go1.18beta1 download

      - name: Build
        run: go1.18beta1 build -v ./...

      - name: Test
        run: go1.18beta1 test -v ./...
